title: Event Types
description: A typology and reference guide for event-driven systems
remote_theme: just-the-docs/just-the-docs

# Just the Docs options
color_scheme: light
color_scheme: event_types
search_enabled: true
search:
  heading_level: 3
  previews: 2

# Aux links shown in top-right
aux_links:
  "View on GitHub": "//github.com/tdonker/event-types"

logo: "/images/evt-logo.png"

# Footer
footer_content: "Copyright &copy; 2026 · Last updated: <span id=\"last-updated\">checking…</span>"
